#!/usr/bin/env node
// Flint design-token generator.
//
// tokens-as-truth: reads docs/design/tokens/tokens.json (the single source of
// truth) and GENERATES the two consumable artifacts:
//   - ios/Flint/App/Tokens.swift   (SwiftUI: dynamic Colors, spacing, radius, fonts)
//   - web/src/tokens.css           (CodeMirror/webview: CSS custom properties)
//
// Never hand-edit the generated files. Edit tokens.json and re-run:
//   node scripts/gen-tokens.mjs
//
// Mirrors the repo's files-as-truth discipline: the JSON is canonical, the
// Swift/CSS are disposable, rebuildable indexes.

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const T = JSON.parse(readFileSync(resolve(root, "docs/design/tokens/tokens.json"), "utf8"));

// --- resolution -----------------------------------------------------------

// Resolve a primitive reference ("warm.900", "spark.500", "alpha.spark-selection")
// or a literal ("#EDEBE6", "rgba(...)") to a concrete CSS color string.
function resolvePrimitive(v) {
  if (typeof v !== "string") throw new Error("expected color string, got " + JSON.stringify(v));
  if (v.startsWith("#") || v.startsWith("rgb")) return v;
  const [group, key] = v.split(".");
  const val = T.primitive?.[group]?.[key];
  if (!val) throw new Error("unresolved primitive ref: " + v);
  return val;
}

// CSS color string -> {r,g,b,a} in 0..1 for Swift.
function parseColor(css) {
  if (css.startsWith("#")) {
    const h = css.slice(1);
    return {
      r: parseInt(h.slice(0, 2), 16) / 255,
      g: parseInt(h.slice(2, 4), 16) / 255,
      b: parseInt(h.slice(4, 6), 16) / 255,
      a: 1,
    };
  }
  const m = css.match(/rgba?\(([^)]+)\)/);
  const [r, g, b, a = "1"] = m[1].split(",").map((s) => s.trim());
  return { r: +r / 255, g: +g / 255, b: +b / 255, a: +a };
}

const f = (n) => n.toFixed(4).replace(/0+$/, "").replace(/\.$/, ".0");
const swiftUIColor = (css) => {
  const c = parseColor(css);
  return `UIColor(red: ${f(c.r)}, green: ${f(c.g)}, blue: ${f(c.b)}, alpha: ${f(c.a)})`;
};

// kebab-case -> camelCase for Swift identifiers.
const camel = (s) => s.replace(/-([a-z])/g, (_, c) => c.toUpperCase());

// --- collect mode-aware colors --------------------------------------------

// name -> { dark, light } resolved to CSS strings.
const colors = {};
for (const [name, val] of Object.entries(T.semantic.color)) {
  if (name === "comment") continue;
  colors[name] = { dark: resolvePrimitive(val.dark), light: resolvePrimitive(val.light) };
}
for (const [name, val] of Object.entries(T.semantic.paper)) {
  if (name === "comment") continue;
  colors["paper-" + name] = { dark: resolvePrimitive(val.dark), light: resolvePrimitive(val.light) };
}

// Syntax tokens are aliases onto existing semantic color names.
const syntaxAliases = {}; // varName -> semantic name it points to
for (const [name, val] of Object.entries(T.semantic.syntax)) {
  if (name === "comment") continue;
  if (val.ref) syntaxAliases["syntax-" + name] = val.ref;
  if (val.bg) syntaxAliases["syntax-" + name + "-bg"] = val.bg;
}

// --- CSS ------------------------------------------------------------------

function genCSS() {
  const L = [];
  L.push("/* GENERATED by scripts/gen-tokens.mjs from docs/design/tokens/tokens.json. Do not edit by hand. */");
  L.push("/* Flint is dark-first: :root holds dark; light is the derived override. */");
  L.push("");

  const colorVars = (mode) =>
    Object.entries(colors).map(([n, v]) => `  --flint-${n}: ${v[mode]};`).join("\n");

  const aliasVars = Object.entries(syntaxAliases)
    .map(([n, ref]) => `  --flint-${n}: var(--flint-${ref});`).join("\n");

  const scalarVars = [];
  for (const [k, v] of Object.entries(T.space)) if (k !== "comment") scalarVars.push(`  --flint-space-${k}: ${v}px;`);
  for (const [k, v] of Object.entries(T.radius)) if (k !== "comment") scalarVars.push(`  --flint-radius-${k}: ${v}px;`);
  scalarVars.push(`  --flint-font-serif: ${T.type.family.serif.css};`);
  scalarVars.push(`  --flint-font-sans: ${T.type.family.sans.css};`);
  scalarVars.push(`  --flint-font-mono: ${T.type.family.mono.css};`);
  for (const [k, v] of Object.entries(T.type.reading)) {
    if (typeof v !== "object" || v.size == null) continue;
    scalarVars.push(`  --flint-reading-${k}-size: ${v.size}px;`);
    scalarVars.push(`  --flint-reading-${k}-lh: ${v.lineHeight};`);
  }
  scalarVars.push(`  --flint-reading-measure: ${T.type.reading.measure};`);
  scalarVars.push(`  --flint-code-size: ${T.type.code.size}px;`);
  scalarVars.push(`  --flint-code-lh: ${T.type.code.lineHeight};`);
  for (const [k, v] of Object.entries(T.motion.duration)) scalarVars.push(`  --flint-duration-${k}: ${v}ms;`);
  for (const [k, v] of Object.entries(T.motion.easing)) scalarVars.push(`  --flint-ease-${k}: ${v};`);

  L.push(":root {");
  L.push(colorVars("dark"));
  L.push(aliasVars);
  L.push(scalarVars.join("\n"));
  L.push("}");
  L.push("");
  L.push("/* Light is derived. Follows the system by default; force with [data-theme]. */");
  L.push("@media (prefers-color-scheme: light) {");
  L.push("  :root:not([data-theme=\"dark\"]) {");
  L.push(colorVars("light").replace(/^/gm, "  "));
  L.push("  }");
  L.push("}");
  L.push("[data-theme=\"light\"] {");
  L.push(colorVars("light"));
  L.push("}");
  L.push("[data-theme=\"dark\"] {");
  L.push(colorVars("dark"));
  L.push("}");
  L.push("");
  return L.join("\n");
}

// --- Swift ----------------------------------------------------------------

function genSwift() {
  const L = [];
  L.push("// GENERATED by scripts/gen-tokens.mjs from docs/design/tokens/tokens.json. Do not edit by hand.");
  L.push("// Flint is dark-first; Colors auto-adapt via UIColor dynamic providers.");
  L.push("");
  L.push("import SwiftUI");
  L.push("");
  L.push("/// Semantic colors. Reference these — never raw hex — in views.");
  L.push("public enum FlintColor {");
  for (const [name, v] of Object.entries(colors)) {
    const id = camel(name);
    L.push(`    public static let ${id} = Color(uiColor: UIColor { tc in`);
    L.push(`        tc.userInterfaceStyle == .light ? ${swiftUIColor(v.light)} : ${swiftUIColor(v.dark)}`);
    L.push(`    })`);
  }
  // syntax aliases
  for (const [name, ref] of Object.entries(syntaxAliases)) {
    L.push(`    public static let ${camel(name)} = ${camel(ref)}`);
  }
  L.push("}");
  L.push("");
  L.push("/// 4pt spacing grid.");
  L.push("public enum FlintSpace {");
  for (const [k, v] of Object.entries(T.space)) if (k !== "comment") L.push(`    public static let s${k}: CGFloat = ${v}`);
  L.push("}");
  L.push("");
  L.push("/// Corner radii. Use with RoundedRectangle(cornerRadius:style:.continuous).");
  L.push("public enum FlintRadius {");
  for (const [k, v] of Object.entries(T.radius)) if (k !== "comment") L.push(`    public static let ${k}: CGFloat = ${v}`);
  L.push("}");
  L.push("");
  L.push("/// Type tokens. Reading = New York (.serif); UI prefers Dynamic Type styles.");
  L.push("public enum FlintFont {");
  for (const [k, v] of Object.entries(T.type.reading)) {
    if (typeof v !== "object" || v.size == null) continue;
    const design = ".serif";
    const weight = v.weight ? `.weight(.${v.weight})` : "";
    L.push(`    public static let reading${k[0].toUpperCase() + k.slice(1)} = Font.system(size: ${v.size}, design: ${design})${weight}`);
  }
  L.push(`    public static let code = Font.system(size: ${T.type.code.size}, design: .monospaced)`);
  L.push("}");
  L.push("");
  L.push("/// Animation durations (seconds).");
  L.push("public enum FlintMotion {");
  for (const [k, v] of Object.entries(T.motion.duration)) L.push(`    public static let ${k}: Double = ${(v / 1000).toFixed(3)}`);
  L.push("}");
  L.push("");
  return L.join("\n");
}

// --- write ----------------------------------------------------------------

const cssPath = resolve(root, "web/src/tokens.css");
const swiftPath = resolve(root, "ios/Flint/App/Tokens.swift");
mkdirSync(dirname(cssPath), { recursive: true });
mkdirSync(dirname(swiftPath), { recursive: true });
writeFileSync(cssPath, genCSS());
writeFileSync(swiftPath, genSwift());
console.log("Generated:\n  " + cssPath + "\n  " + swiftPath);
