import * as esbuild from "esbuild";
import { cpSync, existsSync, mkdirSync, rmSync } from "node:fs";

const watch = process.argv.includes("--watch");
const outdir = "dist";

rmSync(outdir, { recursive: true, force: true });
mkdirSync(outdir, { recursive: true });
cpSync("src/index.html", `${outdir}/index.html`);
// tokens.css is generated by scripts/gen-tokens.mjs (gitignored). The editor
// theme reads its CSS variables, so ship it alongside the bundle. Generation
// runs before this in make/Xcode; guard in case it hasn't yet.
if (existsSync("src/tokens.css")) {
  cpSync("src/tokens.css", `${outdir}/tokens.css`);
} else {
  console.warn("[flint-web] src/tokens.css missing — run `make tokens` first");
}

const options = {
  entryPoints: ["src/index.ts"],
  bundle: true,
  format: "esm",
  outfile: `${outdir}/app.js`,
  sourcemap: true,
  // WKWebView on iOS 26 — modern Safari engine.
  target: ["safari18"],
};

if (watch) {
  const ctx = await esbuild.context(options);
  await ctx.watch();
  console.log("[flint-web] watching…");
} else {
  await esbuild.build(options);
  console.log("[flint-web] bundle built → dist/");
}
